
# Build stage
FROM eclipse-temurin:21-jdk AS build
WORKDIR /app
COPY gradle gradle
COPY gradlew build.gradle settings.gradle .
COPY src src
RUN sed -i 's/\r$//' gradlew
RUN ./gradlew --no-daemon clean bootJar

# Runtime stage
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
HEALTHCHECK CMD curl --fail http://localhost:8080 || exit 1
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]