name: CI (Test/Build/Release)

on:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Dépendances Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Dépendances Node
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: front/package-lock.json

      - name: Run tests
        run: bash ./run_all_test.sh

      - name: Test Report
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }}
        with:
          name: Tests
          path: test_result/**/*.xml
          reporter: java-junit 

  build-and-push-image:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: back
          push: true
          tags: ghcr.io/denisndj/oc_ndjandadenis_projet6_back:latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: front
          push: true
          tags: ghcr.io/denisndj/oc_ndjandadenis_projet6_front:latest

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Prep frontend
        run: |
          cd front
          npm install --no-save semantic-release @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      - name: Prep backend
        run: |
          cd back
          npm init
          npm install --no-save semantic-release @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      - name: Semantic Release Front
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24
          working_directory: front
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      - name: Semantic Release Front
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24
          working_directory: back
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}